import { Sparkles } from "lucide-react";
import { landscapeFrom } from "@/lib/career-graph/engine";
import { narrateLandscape } from "@/lib/ai/narrate";
import { createClient } from "@/lib/supabase/server";
import { getSessionUser } from "@/lib/auth";

// A cheap stable hash of the candidate's skills, so a cached narration is reused
// until the skills (their "shape") actually change.
function shapeHash(skills: string[]): string {
  return [...skills].map((s) => s.toLowerCase()).sort().join("|");
}

// Streamed separately via Suspense so the map renders instantly. Caches the
// result per (candidate, root role) so revisits are instant and we don't pay for
// a fresh AI call every time.
export async function LandscapeNarration({
  rootRoleId,
  roleTitle,
  skills,
}: {
  rootRoleId: string;
  roleTitle: string;
  skills: string[];
}) {
  const user = await getSessionUser();
  const supabase = await createClient();
  const hash = shapeHash(skills);

  // 1. Try the cache.
  if (user) {
    const { data: cached } = await supabase
      .from("narration_cache")
      .select("text, used_ai, shape_hash")
      .eq("profile_id", user.id)
      .eq("root_role_id", rootRoleId)
      .maybeSingle();
    if (cached && cached.shape_hash === hash) {
      return <NarrationBox text={cached.text} usedAI={cached.used_ai} cached />;
    }
  }

  // 2. Generate fresh.
  const moves = landscapeFrom(rootRoleId, skills);
  const narration = await narrateLandscape(roleTitle, moves);

  // 3. Store for next time (best-effort).
  if (user) {
    await supabase.from("narration_cache").upsert(
      {
        profile_id: user.id,
        root_role_id: rootRoleId,
        shape_hash: hash,
        text: narration.text,
        used_ai: narration.usedAI,
      },
      { onConflict: "profile_id,root_role_id" },
    );
  }

  return <NarrationBox text={narration.text} usedAI={narration.usedAI} />;
}

function NarrationBox({
  text,
  usedAI,
  cached,
}: {
  text: string;
  usedAI: boolean;
  cached?: boolean;
}) {
  return (
    <div className="flex gap-3 rounded-xl border bg-primary/5 p-4">
      <Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
      <div>
        <p className="text-sm leading-relaxed">{text}</p>
        <p className="mt-1.5 text-xs text-muted-foreground">
          {usedAI ? "Generated by AI" : "Honest summary"} · navigation, not
          prediction{cached ? " · saved" : ""}
        </p>
      </div>
    </div>
  );
}

export function NarrationSkeleton() {
  return (
    <div className="flex gap-3 rounded-xl border bg-primary/5 p-4">
      <Sparkles className="mt-0.5 h-5 w-5 shrink-0 animate-pulse text-primary" />
      <div className="flex-1 space-y-2">
        <div className="h-3.5 w-full animate-pulse rounded bg-muted" />
        <div className="h-3.5 w-4/5 animate-pulse rounded bg-muted" />
        <div className="h-2.5 w-40 animate-pulse rounded bg-muted" />
      </div>
    </div>
  );
}
