import { Sparkles } from "lucide-react";
import { landscapeFrom } from "@/lib/career-graph/engine";
import { narrateLandscape } from "@/lib/ai/narrate";

// Streamed separately via Suspense so the map renders instantly while the AI
// narration (a slow LLM call) loads in after.
export async function LandscapeNarration({
  rootRoleId,
  roleTitle,
  skills,
}: {
  rootRoleId: string;
  roleTitle: string;
  skills: string[];
}) {
  const moves = landscapeFrom(rootRoleId, skills);
  const narration = await narrateLandscape(roleTitle, moves);

  return (
    <div className="flex gap-3 rounded-xl border bg-primary/5 p-4">
      <Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
      <div>
        <p className="text-sm leading-relaxed">{narration.text}</p>
        <p className="mt-1.5 text-xs text-muted-foreground">
          {narration.usedAI
            ? "Generated by AI · navigation, not prediction"
            : "Honest summary · navigation, not prediction"}
        </p>
      </div>
    </div>
  );
}

export function NarrationSkeleton() {
  return (
    <div className="flex gap-3 rounded-xl border bg-primary/5 p-4">
      <Sparkles className="mt-0.5 h-5 w-5 shrink-0 animate-pulse text-primary" />
      <div className="flex-1 space-y-2">
        <div className="h-3.5 w-full animate-pulse rounded bg-muted" />
        <div className="h-3.5 w-4/5 animate-pulse rounded bg-muted" />
        <div className="h-2.5 w-40 animate-pulse rounded bg-muted" />
      </div>
    </div>
  );
}
