"use client";

import { useState, useTransition } from "react";
import {
  Loader2,
  Route,
  Sparkles,
  CheckCircle2,
  Circle,
  Building2,
  Clock,
} from "lucide-react";
import { toast } from "sonner";
import { buildRoadmap } from "./roadmap-action";
import type { Roadmap } from "@/lib/ai/roadmap";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { months } from "@/lib/format";

export function RoadmapDialog({
  targetRoleId,
  targetTitle,
  fromTitle,
}: {
  targetRoleId: string;
  targetTitle: string;
  fromTitle: string;
}) {
  const [open, setOpen] = useState(false);
  const [company, setCompany] = useState("");
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [pending, startTransition] = useTransition();

  function generate() {
    startTransition(async () => {
      const res = await buildRoadmap({ targetRoleId, company });
      if (res.error) toast.error(res.error);
      else if (res.roadmap) setRoadmap(res.roadmap);
    });
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        setOpen(o);
        if (!o) setRoadmap(null);
      }}
    >
      <DialogTrigger asChild>
        <Button variant="outline" className="w-full gap-2">
          <Route className="h-4 w-4" />
          Generate my roadmap
        </Button>
      </DialogTrigger>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Route className="h-5 w-5 text-primary" />
            Roadmap to {targetTitle}
          </DialogTitle>
          <DialogDescription>
            A personalised plan from {fromTitle}, built around your skill gap.
          </DialogDescription>
        </DialogHeader>

        {!roadmap ? (
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="company">Targeting a specific company? (optional)</Label>
              <Input
                id="company"
                value={company}
                onChange={(e) => setCompany(e.target.value)}
                placeholder="e.g. Grab, Maybank, a fintech startup…"
              />
              <p className="text-xs text-muted-foreground">
                We&apos;ll tailor the plan to what that kind of employer values.
              </p>
            </div>
            <Button onClick={generate} disabled={pending} className="w-full gap-2">
              {pending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="h-4 w-4" />
              )}
              {pending ? "Building your roadmap…" : "Generate roadmap"}
            </Button>
          </div>
        ) : (
          <RoadmapView roadmap={roadmap} onRegenerate={() => setRoadmap(null)} />
        )}
      </DialogContent>
    </Dialog>
  );
}

function RoadmapView({
  roadmap,
  onRegenerate,
}: {
  roadmap: Roadmap;
  onRegenerate: () => void;
}) {
  return (
    <div className="space-y-5">
      {/* Summary */}
      <div className="flex gap-2 rounded-lg bg-primary/5 p-3">
        <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
        <div>
          <p className="text-sm leading-relaxed">{roadmap.summary}</p>
          <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" /> ~{months(roadmap.totalMonthsEstimate)} total
            </span>
            {roadmap.company && (
              <span className="flex items-center gap-1">
                <Building2 className="h-3 w-3" /> Tailored for {roadmap.company}
              </span>
            )}
            <span>{roadmap.usedAI ? "Generated by AI" : "Structured plan"}</span>
          </div>
        </div>
      </div>

      {/* Phases — roadmap.sh style vertical track */}
      <div className="relative space-y-6 pl-6">
        <div className="absolute bottom-2 left-[7px] top-2 w-px bg-border" />
        {roadmap.phases.map((phase, pi) => (
          <div key={pi} className="relative">
            <div className="absolute -left-6 top-1 flex h-3.5 w-3.5 items-center justify-center rounded-full border-2 border-primary bg-background" />
            <div>
              <h3 className="text-sm font-semibold">{phase.name}</h3>
              <p className="text-xs text-muted-foreground">{phase.goal}</p>
            </div>
            <div className="mt-3 space-y-2">
              {phase.steps.map((step, si) => (
                <div key={si} className="rounded-lg border bg-card p-3">
                  <div className="flex items-start gap-2">
                    <Circle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium">{step.title}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">
                        {step.detail}
                      </p>
                      {step.skills.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-1">
                          {step.skills.map((s) => (
                            <Badge key={s} variant="secondary" className="gap-1 text-[10px]">
                              <CheckCircle2 className="h-2.5 w-2.5 text-emerald-500" />
                              {s}
                            </Badge>
                          ))}
                        </div>
                      )}
                      {step.resource && (
                        <p className="mt-1.5 text-[11px] italic text-muted-foreground">
                          → {step.resource}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <Button variant="ghost" size="sm" onClick={onRegenerate} className="w-full">
        Generate a different roadmap
      </Button>
    </div>
  );
}
