import { ROLE_BY_ID } from "./seed-data";

// Synthetic candidate personas so the employer talent pool feels alive even
// before real candidates sign up. Clearly synthetic (no real PII), but realistic
// for the Malaysian market. Real signed-up candidates are merged in alongside.
export interface Persona {
  id: string; // synthetic id, prefixed so it never collides with real uuids
  fullName: string;
  headline: string;
  location: string;
  university: string;
  seedRoleId: string;
  skills: string[];
  findability: "open" | "quiet";
  synthetic: true;
}

export const PERSONAS: Persona[] = [
  {
    id: "p_aisyah",
    fullName: "Aisyah Rahman",
    headline: "Software Engineer, 2 yrs, fintech",
    location: "Kuala Lumpur",
    university: "Universiti Malaya",
    seedRoleId: "r_swe",
    skills: ["TypeScript", "React", "Node.js", "SQL", "Git"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_wei",
    fullName: "Tan Wei Sheng",
    headline: "Data Analyst moving toward data science",
    location: "Petaling Jaya",
    university: "Universiti Sains Malaysia",
    seedRoleId: "r_data_analyst",
    skills: ["SQL", "Python", "Data Visualization", "Statistics", "Excel"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_arjun",
    fullName: "Arjun Pillai",
    headline: "Senior Software Engineer, payments",
    location: "Kuala Lumpur",
    university: "Universiti Teknologi Malaysia",
    seedRoleId: "r_senior_swe",
    skills: ["System Design", "TypeScript", "Architecture", "Cloud", "Mentoring"],
    findability: "quiet",
    synthetic: true,
  },
  {
    id: "p_mei",
    fullName: "Lim Mei Ling",
    headline: "Associate PM, consumer apps",
    location: "Kuala Lumpur",
    university: "Monash Malaysia",
    seedRoleId: "r_assoc_pm",
    skills: ["Communication", "Data Analysis", "UX", "Stakeholder Management"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_faiz",
    fullName: "Muhammad Faiz",
    headline: "Fresh CS grad, strong fundamentals",
    location: "Shah Alam",
    university: "UiTM",
    seedRoleId: "r_grad_swe",
    skills: ["JavaScript", "Git", "SQL", "Problem Solving", "Communication"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_priya",
    fullName: "Priya Nair",
    headline: "Data Scientist, pricing & experimentation",
    location: "Petaling Jaya",
    university: "Universiti Malaya",
    seedRoleId: "r_data_scientist",
    skills: ["Python", "Machine Learning", "Statistics", "SQL", "Communication"],
    findability: "quiet",
    synthetic: true,
  },
  {
    id: "p_hakim",
    fullName: "Hakim Abdullah",
    headline: "DevOps engineer, cloud platforms",
    location: "Cyberjaya",
    university: "Multimedia University",
    seedRoleId: "r_devops",
    skills: ["Cloud", "Docker", "Kubernetes", "CI/CD", "Linux"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_sarah",
    fullName: "Sarah Lee",
    headline: "Product Designer, research-led",
    location: "Kuala Lumpur",
    university: "The One Academy",
    seedRoleId: "r_ux_designer",
    skills: ["Figma", "User Research", "Prototyping", "UX", "Communication"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_daniel",
    fullName: "Daniel Wong",
    headline: "Digital marketer eyeing growth roles",
    location: "Kuala Lumpur",
    university: "Sunway University",
    seedRoleId: "r_marketing_exec",
    skills: ["Content", "SEO", "Social Media", "Analytics", "Communication"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_nadia",
    fullName: "Nadia Ismail",
    headline: "Business Analyst, digital banking",
    location: "Kuala Lumpur",
    university: "International Islamic University",
    seedRoleId: "r_biz_analyst",
    skills: ["SQL", "Requirements", "Communication", "Process Design", "Data Analysis"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_jaya",
    fullName: "Jayakumar Raj",
    headline: "Software Engineer, strong backend",
    location: "George Town, Penang",
    university: "Universiti Sains Malaysia",
    seedRoleId: "r_swe",
    skills: ["Node.js", "SQL", "System Design", "TypeScript", "Git"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_chong",
    fullName: "Chong Kar Wai",
    headline: "ML Engineer, computer vision",
    location: "Cyberjaya",
    university: "Multimedia University",
    seedRoleId: "r_ml_engineer",
    skills: ["Python", "Machine Learning", "Docker", "Cloud", "System Design"],
    findability: "quiet",
    synthetic: true,
  },
  {
    id: "p_iman",
    fullName: "Iman Sofea",
    headline: "Fresh grad, eager data analyst",
    location: "Kuala Lumpur",
    university: "Universiti Putra Malaysia",
    seedRoleId: "r_data_analyst",
    skills: ["SQL", "Excel", "Data Visualization", "Communication"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_ravi",
    fullName: "Ravindran Murugan",
    headline: "Senior engineer moving toward EM",
    location: "Petaling Jaya",
    university: "Universiti Teknologi Malaysia",
    seedRoleId: "r_senior_swe",
    skills: ["System Design", "Mentoring", "Architecture", "Cloud", "TypeScript"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_yyin",
    fullName: "Yap Yi Xin",
    headline: "Product Manager, marketplace",
    location: "Kuala Lumpur",
    university: "Universiti Malaya",
    seedRoleId: "r_product_manager",
    skills: ["Product Strategy", "Data Analysis", "Stakeholder Management", "UX", "Communication"],
    findability: "quiet",
    synthetic: true,
  },
  {
    id: "p_farah",
    fullName: "Farah Adriana",
    headline: "Growth marketer, performance & SEO",
    location: "Shah Alam",
    university: "Taylor's University",
    seedRoleId: "r_growth_manager",
    skills: ["Analytics", "SEO", "Experimentation", "Data Analysis", "Content"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_brian",
    fullName: "Brian Tan",
    headline: "UX designer, fintech apps",
    location: "Kuala Lumpur",
    university: "The One Academy",
    seedRoleId: "r_ux_designer",
    skills: ["Figma", "Prototyping", "User Research", "UX"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_aina",
    fullName: "Aina Maisarah",
    headline: "Graduate developer, web focus",
    location: "Johor Bahru",
    university: "Universiti Tun Hussein Onn",
    seedRoleId: "r_grad_swe",
    skills: ["JavaScript", "Git", "Problem Solving", "Communication"],
    findability: "open",
    synthetic: true,
  },
  {
    id: "p_sanjay",
    fullName: "Sanjay Kumar",
    headline: "DevOps engineer, multi-cloud",
    location: "Bayan Lepas, Penang",
    university: "Universiti Sains Malaysia",
    seedRoleId: "r_devops",
    skills: ["Cloud", "Kubernetes", "Terraform", "CI/CD", "Linux"],
    findability: "open",
    synthetic: true,
  },
];

export function personaRoleTitle(p: Persona): string {
  return ROLE_BY_ID[p.seedRoleId]?.title ?? "—";
}
